from enum import Enum


class NotificationType(Enum):
    PHYSIOTHERAPIST_REGISTERED = "PHYSIOTHERAPIST_REGISTERED"
    PHYSIOTHERAPIST_VERIFIED = "PHYSIOTHERAPIST_VERIFIED"
    PHYSIOTHERAPIST_REJECTED = "PHYSIOTHERAPIST_REJECTED"
